server:
  port: 8080
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: seon
    password: tjsalstn12

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false #jpa의 기본 넘버링 전략을 따르지않음
    show-sql: true #빌드 시 sql문 보여줌
    properties:    #빌드 시 sql문을 깔끔하게 보여줌
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
